######### OPTIONS #############################################################
--biblio-static-entries=\
(incremental) IDs of the bibliographic entries to render in the bibliography\n\
even if not cited via taglets.\n\
NOTE: This option is incremental, that is it can be repeated with a modifier\n\
prefix (+ or -) to, respectively, add or remove elements; without modifier,\n\
the collection is overridden.
--biblio-used-only=\
Whether only bibliographic entries actually cited via taglets are rendered\n\
into the bibliography (that is, reference list).
