/*
  SPDX-FileCopyrightText: 2025-2026 Stefano Chizzolini and contributors

  SPDX-License-Identifier: LGPL-3.0-only

  This file (DocReuseTaglet.java) is part of jada-ext module in Jada project
  <https://github.com/pdfclown/jada>

  DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER. If you reuse (entirely or partially)
  this file, you MUST add your own copyright notice in a separate comment block above this file
  header, listing the main changes you applied to the original source.
 */
package org.pdfclown.jada.ext.taglet;

import static org.pdfclown.common.util.Strings.EMPTY;

import com.sun.source.doctree.DocTree;
import java.util.EnumSet;
import java.util.List;
import java.util.Set;
import javax.lang.model.element.Element;
import jdk.javadoc.doclet.Taglet;
import org.pdfclown.jada.ext.proc.DocReuseTagletProcessor;

/**
 * Javadoc fragment reuse taglet.
 * <p>
 * Its specializations make Javadoc fragments reusable, similarly to standard {@code @inheritDoc}
 * tag, but applicable to any source code element (for example, to reuse Javadoc contents of
 * overloaded methods) and to any extent (from a single paragraph to the whole comment body, grouped
 * as a single fragment or as multiple ones):
 * </p>
 * <ul>
 * <li>{@link DocTaglet @jada.doc} tag (<b>source</b>) defines a Javadoc fragment, associating it to
 * a key</li>
 * <li>{@link ReuseDocTaglet @jada.reuseDoc} tag (<b>target</b>) references a Javadoc fragment by
 * key in the location where it must be placed (similarly to standard {@code @inheritDoc} tag)</li>
 * </ul>
 * <h4>Usage</h4>
 * <p>
 * The fragment definition MUST terminate with a <code>{</code>{@code @jada.doc END}<code>}</code>
 * tag within the same Javadoc comment ({@code END} is a pseudo-key directive) — for example:
 * </p>
 * <pre class="lang-java" data-line="6-8"><code>
 * package org.example.mypkg;
 * . . .
 * public class MyClass {
 *   . . .
 *   &#47;**
 *    * <span style="background-color:yellow;color:black;">{&#64;jada.doc }
 *    * Gets the corresponding string.
 *    * {&#64;jada.doc END}</span>
 *    *&#47;
 *   public String myMethod(int myParam, Object myParam2) {
 *     . . .
 *   }
 * }</code></pre>
 * <p>
 * Then it can be reused in any compilation unit within the same project module, provided it is
 * referenced appropriately (the reference resolution algorithm, described in the next section, is
 * similar to the <a href=
 * "https://docs.oracle.com/en/java/javase/22/docs/specs/javadoc/doc-comment-spec.html#references">standard
 * mechanism for element reference resolution</a> ) — for example:
 * </p>
 * <pre class="lang-java" data-line="8"><code>
 * package org.example.anotherpkg;
 *
 * import org.example.mypkg.MyClass;
 * . . .
 * public class AnotherClass {
 *   . . .
 *   &#47;**
 *    * <span style=
"background-color:yellow;color:black;">{&#64;jada.reuseDoc MyClass#myMethod(*)}</span>
 *    *&#47;
 *   public String anotherMethod(int myParam) {
 *     . . .
 *   }
 * }</code></pre>
 * <p>
 * Once its configuration is active (see dedicated section here below), the target fragments (that
 * is, {@code @jada.reuseDoc}) are automatically synchronized with the corresponding source
 * fragments (that is, {@code @jada.doc}) on build system execution; in case of IDE integration
 * (such as m2e/m2eclipse for Eclipse IDE), any change to source fragments is immediately propagated
 * to the whole project module. After the synchronization, the example here above will look like
 * this:
 * </p>
 * <pre class="lang-java" data-line="8-10"><code>
 * package org.example.anotherpkg;
 *
 * import org.example.mypkg.MyClass;
 * . . .
 * public class AnotherClass {
 *   . . .
 *   &#47;**
 *    * <span style="background-color:yellow;color:black;">{&#64;jada.reuseDoc MyClass#myMethod(*)}
 *    * Gets the corresponding string.
 *    * {&#64;jada.reuseDoc END}</span>
 *    *&#47;
 *   public String anotherMethod(int myParam) {
 *     . . .
 *   }
 * }</code></pre>
 * <p>
 * Finally, these tags are automatically removed from the corresponding documentation generated by
 * the javadoc tool.
 * </p>
 * <h5>Reference resolution</h5>
 * <p>
 * As anticipated, <i>the fragments can be referenced by {@code @jada.reuseDoc} via constructs
 * mostly equivalent to the <a href=
 * "https://docs.oracle.com/en/java/javase/22/docs/specs/javadoc/doc-comment-spec.html#references">standard
 * Javadoc references for API elements</a></i>. In particular:
 * </p>
 * <ul>
 * <li>hash-prefixed reference for class members (fields, methods, constructors — for example:
 * {@code #myField}, {@code #myMethod(*)}, {@code #MyClass(*)}). NOTE: Contrary to standard, the
 * {@code #} is always mandatory; method references are discussed here below.</li>
 * <li>dot-separated relative reference for local inner types, imported types, and local
 * package-level types</li>
 * <li>dot-separated fully-qualified reference for any module-level type</li>
 * </ul>
 * <p>
 * <i>Besides the standard conventions, the tags define also some custom conventions</i>:
 * </p>
 * <ul>
 * <li><b>method references</b>: for the sake of simplicity, methods (and constructors) are
 * referenced without parameters; to avoid ambiguities with parameterless overloads or other members
 * (such as fields), all method references MUST be denoted by {@code (*)} — for example:
 * <pre class="lang-java" data-line="8"><code>
 * package org.example.anotherpkg;
 *
 * import org.example.mypkg.MyClass;
 * . . .
 * public class AnotherClass {
 *   . . .
 *   &#47;**
 *    * <span style=
"background-color:yellow;color:black;">{&#64;jada.reuseDoc MyClass#myMethod(*)}</span>
 *    *&#47;
 *   public String anotherMethod(int myParam) {
 *     . . .
 *   }
 * }</code></pre>
 * <p>
 * will reference
 * </p>
 * <pre class="lang-java" data-line="6-8"><code>
 * package org.example.mypkg;
 * . . .
 * public class MyClass {
 *   . . .
 *   &#47;**
 *    * <span style="background-color:yellow;color:black;">{&#64;jada.doc }
 *    * Gets the corresponding string.
 *    * {&#64;jada.doc END}</span>
 *    *&#47;
 *   public String myMethod(int myParam, Object myParam2) {
 *     . . .
 *   }
 * }</code></pre>
 * <p>
 * NOTE: When method overloads are referenced within any of their own Javadoc comments, their
 * references can be implicit — for example:
 * </p>
 * <pre class="lang-java" data-line="6"><code>
 * package org.example.mypkg;
 * . . .
 * public class MyClass {
 *   . . .
 *   &#47;**
 *    * <span style="background-color:yellow;color:black;">{&#64;jada.reuseDoc }</span>
 *    *&#47;
 *   public String myMethod(int myParam) {
 *     myMethod(myParam, null);
 *   }
 *
 *   &#47;**
 *    * {&#64;jada.doc }
 *    * Gets the corresponding string.
 *    * {&#64;jada.doc END}
 *    *&#47;
 *   public String myMethod(int myParam, Object myParam2) {
 *     . . .
 *   }
 * }</code></pre></li>
 * <li><b>fragment names</b>: generally, fragments don't need explicit names (their implicit name
 * corresponds to the syntactic element their containing Javadoc comment is associated to — for
 * example, a method, a type, ...); nonetheless, <i>in case of multiple fragments within the same
 * Javadoc comment, the additional ones MUST be disambiguated with a name</i> — for example:
 * <pre class="lang-java" data-line="10-12"><code>
 * package org.example.mypkg;
 * . . .
 * public class MyClass {
 *   . . .
 *   &#47;**
 *    * {&#64;jada.doc }
 *    * Gets the corresponding string.
 *    * {&#64;jada.doc END}
 *    *
 *    * <span style="background-color:yellow;color:black;">{&#64;jada.doc myExtraFragment}
 *    * Additional contents.
 *    * {&#64;jada.doc END}</span>
 *    *&#47;
 *   public String myMethod(int myParam, Object myParam2) {
 *     . . .
 *   }
 * }</code></pre>
 * <p>
 * will be referenced like this (note the {@code :} to denote the fragment name):
 * </p>
 * <pre class="lang-java" data-line="10"><code>
 * package org.example.anotherpkg;
 *
 * import org.example.mypkg.MyClass;
 * . . .
 * public class AnotherClass {
 *   . . .
 *   &#47;**
 *    * {&#64;jada.reuseDoc MyClass#myMethod(*)}
 *    *
 *    * <span style=
"background-color:yellow;color:black;">{&#64;jada.reuseDoc MyClass#myMethod(*):myExtraFragment}</span>
 *    *&#47;
 *   public String anotherMethod(int myParam) {
 *     . . .
 *   }
 * }</code></pre></li>
 * <p>
 * <span class="important">IMPORTANT: DO NOT use all-uppercase names as fragment names</span> (for
 * further information, see next point "reserved names").
 * </p>
 * <li><b>reserved names</b>: <i>within these tags, all-uppercase names are reserved</i> (they MUST
 * NOT be used to name fragments). In case of collision (for example, the unlikely case of a class
 * named {@code END}), the API element MUST be qualified to avoid ambiguities (for example,
 * {@code MyOuterType.END}): <pre class="lang-java" data-line="24,28"><code>
 * package org.example.mypkg;
 * . . .
 * public class MyOuterType {
 *   &#47;**
 *    * {&#64;jada.doc }
 *    * A class with the same name as the ending tag directive.
 *    * {&#64;jada.doc END}
 *    *&#47;
 *   class END {
 *   }
 *
 *   &#47;**
 *    * {&#64;jada.doc }
 *    * A field with the same name as the ending tag directive.
 *    * {&#64;jada.doc END}
 *    *&#47;
 *   static final String END = "END";
 *
 *   &#47;**
 *    * {&#64;jada.doc }
 *    * Gets the corresponding string.
 *    * {&#64;jada.doc END}
 *    *
 *    * <span style=
"background-color:yellow;color:black;">{&#64;jada.reuseDoc MyOuterType.END}</span>
 *    * A class with the same name as the ending tag directive.
 *    * {&#64;jada.reuseDoc END}
 *    *
 *    * <span style="background-color:yellow;color:black;">{&#64;jada.reuseDoc #END}</span>
 *    * A field with the same name as the ending tag directive.
 *    * {&#64;jada.reuseDoc END}
 *    *&#47;
 *   public String myMethod(int myParam, Object myParam2) {
 *     . . .
 *   }
 * }</code></pre></li>
 * </ul>
 * <h4>Configuration</h4>
 * <p>
 * <span class="important">Since Javadoc fragment reuse tags don't belong to the standard Javadoc
 * toolkit, in order to activate their behavior the build configuration must be set as
 * follows</span>.
 * </p>
 * <h5>Maven</h5>
 * <p>
 * In the {@code pom.xml} file of your project (replace <code>${jada.version}</code> with the latest
 * version available):
 * </p>
 * <ol>
 * <li>add {@code jada-maven-plugin} for source
 * processing:<pre class="lang-xml" data-line="5-19"><code>
 * &lt;project&gt;
 *   &lt;build&gt;
 *     &lt;plugins&gt;
 *       . . .
 *       <span style="background-color:yellow;color:black;">&lt;plugin&gt;
 *         &lt;groupId&gt;org.pdfclown&lt;/groupId&gt;
 *         &lt;artifactId&gt;jada-maven-plugin&lt;/artifactId&gt;
 *         &lt;version&gt;${jada.version}&lt;/version&gt;
 *         &lt;executions&gt;
 *           &lt;execution&gt;
 *             &lt;goals&gt;
 *               &lt;goal&gt;processSource&lt;/goal&gt;
 *             &lt;/goals&gt;
               &lt;configuration&gt;
                 &lt;processors&gt;org.pdfclown.jada.ext.proc.DocReuseTagletProcessor&lt;/processors&gt;
               &lt;/configuration&gt;
 *           &lt;/execution&gt;
 *         &lt;/executions&gt;
 *       &lt;/plugin&gt;</span>
 *     &lt;/plugins&gt;
 *   &lt;/build&gt;
 * &lt;/project&gt;</code></pre></li>
 * <li>add to {@code maven-javadoc-plugin} the Javadoc fragment reuse
 * taglets:<pre class="lang-xml" data-line="10-20"><code>
 * &lt;project&gt;
 *   &lt;build&gt;
 *     &lt;plugins&gt;
 *       &lt;plugin&gt;
 *         &lt;artifactId&gt;maven-javadoc-plugin&lt;/artifactId&gt;
 *         &lt;version&gt;${maven-javadoc-plugin.version}&lt;/version&gt;
 *         &lt;configuration&gt;
 *           . . .
 *           &lt;taglets&gt;
 *             <span style="background-color:yellow;color:black;">&lt;taglet&gt;
 *               &lt;tagletClass&gt;org.pdfclown.jada.ext.taglet.DocTaglet&lt;/tagletClass&gt;
 *               &lt;tagletArtifact&gt;
 *                 &lt;groupId&gt;org.pdfclown&lt;/groupId&gt;
 *                 &lt;artifactId&gt;jada-ext&lt;/artifactId&gt;
 *                 &lt;version&gt;${jada.version}&lt;/version&gt;
 *               &lt;/tagletArtifact&gt;
 *             &lt;/taglet&gt;
 *             &lt;taglet&gt;
 *               &lt;tagletClass&gt;org.pdfclown.jada.ext.taglet.ReuseDocTaglet&lt;/tagletClass&gt;
 *             &lt;/taglet&gt;</span>
 *           &lt;/taglets&gt;
 *         &lt;/configuration&gt;
 *       &lt;/plugin&gt;
 *     &lt;/plugins&gt;
 *   &lt;/build&gt;
 * &lt;/project&gt;</code></pre></li>
 * </ol>
 *
 * @author Stefano Chizzolini
 */
public abstract class DocReuseTaglet implements Taglet {
  @Override
  public Set<Location> getAllowedLocations() {
    return EnumSet.allOf(Location.class);
  }

  @Override
  public boolean isInlineTag() {
    return true;
  }

  /**
   * @implNote Since Javadoc fragment reuse tags are just placeholders for
   *           {@linkplain DocReuseTagletProcessor source-code processing}, their output
   *           representation is empty.
   */
  @Override
  public String toString(List<? extends DocTree> tags, Element element) {
    return EMPTY;
  }
}
