######### OPTIONS #############################################################
--uml-custom-directive=\
(repeatable) Custom directive to include in rendered PlantUML diagrams.
--uml-empty-diagrams-render=\
Render also diagrams which are empty.
--uml-package-deps-check-cyclic=\
Warn on cyclic package dependencies.
--uml-package-deps-exclude=\
(incremental) Names of packages excluded from the package dependencies diagram.\n\
Names can be expressed as globs (with {@code '*'} and {@code '?'} wildcards).\n\
Use 'unnamed' for the default package.\n\
DEFAULT: 'java.*,javax.*'\n\
NOTE: This option is incremental, that is it can be repeated with a modifier\n\
prefix (+ or -) to, respectively, add or remove elements; without modifier,\n\
the collection is overridden.
--uml-type-refs-exclude=\
(incremental) Names of types excluded as reference.\n\
DEFAULT: 'java.lang.Object,java.lang.Enum,java.lang.annotation.Annotation'\n\
NOTE: This option is incremental, that is it can be repeated with a modifier\n\
prefix (+ or -) to, respectively, add or remove elements; without modifier,\n\
the collection is overridden.
--uml-properties-flatten=\
Render JavaBean property accessors as methods in UML rather than fields.
--uml-source-generate=\
Generate PlantUML source files.
--uml-image-dir=\
Directory where UML diagram images are generated.
--uml-image-format=\
(incremental) Image formats to generate UML diagrams in.\n\
One or more of the following values (case-insensitive):{0}\n\
DEFAULT: 'svg'\n\
NOTE: This option is incremental, that is it can be repeated with a modifier\n\
prefix (+ or -) to, respectively, add or remove elements; without modifier,\n\
the collection is overridden.
--uml-package-deps-max-count=\
Maximum number of packages included in the package dependencies diagram.\n\
VALUE: integer number (negative means no limit).\n\
DEFAULT: 10
--uml-server-timeout=\
PlantUML server timeout.\n\
VALUE: integer number.
--uml-server-url=\
Base URL of the PlantUML server to generate diagrams with.
--uml-static-fields-max-count=\
Maximum number of static fields included in class diagrams.\n\
VALUE: integer number.\n\
DEFAULT: 10
