<?xml version="1.0" encoding="UTF-8"?>
<!--
  SPDX-FileCopyrightText: 2025 Stefano Chizzolini and contributors

  SPDX-License-Identifier: LGPL-3.0-only
-->
<project
    xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.pdfclown</groupId>
    <artifactId>jada-parent</artifactId>
    <version>${revision}</version>
    <relativePath>../jada-parent/pom.xml</relativePath>
  </parent>

  <artifactId>jada-uml</artifactId>

  <name>${project.artifactId}</name>
  <description>JadaUML is a Jada doclet extension to add UML diagrams to Javadoc.</description>
  <url>${projectRootUrl}</url>

  <properties>
    <!--
      OVERRIDDEN PROPERTIES
    -->
    <projectJpmsName>org.pdfclown.jada.uml</projectJpmsName>
    <rootdir>${project.basedir}/..</rootdir>

    <!--
      VERSIONS
    -->
    <plantuml.version>1.2025.10</plantuml.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.pdfclown</groupId>
      <artifactId>jada-core</artifactId>
    </dependency>

    <dependency>
      <groupId>commons-io</groupId>
      <artifactId>commons-io</artifactId>
    </dependency>
    <dependency>
      <groupId>net.sourceforge.plantuml</groupId>
      <artifactId>plantuml-asl</artifactId>
      <version>${plantuml.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-lang3</artifactId>
    </dependency>
    <dependency>
      <groupId>org.jsoup</groupId>
      <artifactId>jsoup</artifactId>
    </dependency>
    <dependency>
      <groupId>org.jspecify</groupId>
      <artifactId>jspecify</artifactId>
    </dependency>
    <dependency>
      <groupId>org.pdfclown</groupId>
      <artifactId>pdfclown-common-util</artifactId>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
    </dependency>

    <!--
      TESTING
    -->
    <dependency>
      <groupId>org.pdfclown</groupId>
      <artifactId>jada-build</artifactId>
    </dependency>
    <dependency>
      <groupId>org.pdfclown</groupId>
      <artifactId>jada-core</artifactId>
      <type>test-jar</type>
    </dependency>
  </dependencies>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-javadoc-plugin</artifactId>
          <configuration>
            <dependencyLinks
                combine.children="append">
              <link>
                <groupId>net.sourceforge.plantuml</groupId>
                <artifactId>plantuml-asl</artifactId>
                <url>https://javadoc.io/doc/net.sourceforge.plantuml/plantuml/${plantuml.version}</url>
              </link>
            </dependencyLinks>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>

    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <configuration>
          <artifactSet>
            <includes>
              <include>net.sourceforge.plantuml:plantuml-asl</include>
            </includes>
          </artifactSet>
          <filters>
            <filter>
              <artifact>*:*</artifact>
              <excludes>
                <exclude>META-INF/MANIFEST.MF</exclude>
              </excludes>
            </filter>
          </filters>
          <minimizeJar>true</minimizeJar>
          <!-- TODO exclude unused packages and resources to save space. -->
        </configuration>
        <executions>
          <execution>
            <id>shade-dependencies</id>
            <goals>
              <goal>shade</goal>
            </goals>
            <phase>package</phase>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
