<?xml version="1.0" encoding="UTF-8"?>
<!--
  SPDX-FileCopyrightText: 2025-2026 Stefano Chizzolini and contributors

  SPDX-License-Identifier: LGPL-3.0-only
-->
<project
    xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.pdfclown</groupId>
    <artifactId>jada-parent</artifactId>
    <version>${revision}</version>
    <relativePath>../jada-parent/pom.xml</relativePath>
  </parent>

  <artifactId>jada-core</artifactId>

  <name>${project.artifactId}</name>
  <description>Core component of Jada, an extensible Javadoc doclet combining an
arbitrary doclet with multiple pre- and post-processors to transform its output in more
flexible and convenient ways</description>
  <url>${projectRootUrl}</url>

  <properties>
    <!--
      OVERRIDDEN PROPERTIES
    -->
    <projectJpmsName>org.pdfclown.jada.core</projectJpmsName>
    <rootdir>${project.basedir}/..</rootdir>
    <testJarFiles>org/pdfclown/jada/core/test/**</testJarFiles>
    <testJarPackages>org.pdfclown.jada.core.test</testJarPackages>

    <!--
      VERSIONS
    -->
    <closure-compiler.version>v20240317</closure-compiler.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-lang3</artifactId>
    </dependency>
    <dependency>
      <groupId>org.jspecify</groupId>
      <artifactId>jspecify</artifactId>
    </dependency>
    <dependency>
      <groupId>org.pdfclown</groupId>
      <artifactId>pdfclown-common-util</artifactId>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
    </dependency>

    <!-- System -->
    <dependency>
      <groupId>io.github.classgraph</groupId>
      <artifactId>classgraph</artifactId>
    </dependency>
    <dependency>
      <groupId>org.greenrobot</groupId>
      <artifactId>eventbus-java</artifactId>
    </dependency>

    <!-- Source processing -->
    <dependency>
      <groupId>com.github.javaparser</groupId>
      <artifactId>javaparser-core</artifactId>
    </dependency>
    <dependency>
      <groupId>org.jsoup</groupId>
      <artifactId>jsoup</artifactId>
    </dependency>
    <dependency>
      <groupId>com.google.javascript</groupId>
      <artifactId>closure-compiler</artifactId>
      <version>${closure-compiler.version}</version>
    </dependency>

    <!-- Scripting -->
    <dependency>
      <groupId>org.apache.groovy</groupId>
      <artifactId>groovy</artifactId>
      <version>${groovy.version}</version>
    </dependency>

    <!--
      TESTING
    -->
    <dependency>
      <groupId>org.pdfclown</groupId>
      <artifactId>jada-build</artifactId>
    </dependency>
  </dependencies>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-javadoc-plugin</artifactId>
          <configuration>
            <additionalOptions
                combine.children="append">
              <option>--uml-package-deps-exclude
                +com.github.javaparser.ast*,com.sun.tools.*,io.github.classgraph,org.greenrobot.eventbus</option>
            </additionalOptions>
          </configuration>
          <executions>
            <execution>
              <id>generate-test-javadoc-jar</id>
              <configuration>
                <additionalOptions
                    combine.children="append">
                  <!--
                    NOTE: JadaUML package dependency analyzer currently is unable to tell classpath
                    and source path references apart (in this case, it detects imports from MAIN
                    `org.pdfclown.jada.core` (on classpath), but links TEST `org.pdfclown.jada.core`
                    (on source path) instead), so we have to suppress wrongly-linked dependencies. -->
                  <option>--uml-package-deps-exclude +org.pdfclown.jada.core</option>
                </additionalOptions>
              </configuration>
            </execution>
          </executions>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
</project>
