/*
  SPDX-FileCopyrightText: 2025-2026 Stefano Chizzolini and contributors

  SPDX-License-Identifier: LGPL-3.0-only

  This file (PostTaglet.java) is part of jada-core module in Jada project
  <https://github.com/pdfclown/jada>

  DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER. If you reuse (entirely or partially)
  this file, you MUST add your own copyright notice in a separate comment block above this file
  header, listing the main changes you applied to the original source.
 */
package org.pdfclown.jada.core.taglet;

import static java.util.Objects.requireNonNull;

import com.sun.source.doctree.DocTree;
import java.nio.file.Path;
import java.util.List;
import javax.lang.model.element.Element;
import org.jspecify.annotations.Nullable;
import org.pdfclown.jada.core.Jada;
import org.pdfclown.jada.core.util.lang.LangModels;

/**
 * Jada taglet for post-processing.
 * <p>
 * Useful for manipulating the output generated by the {@linkplain Jada#getBase() doclet}.
 * </p>
 *
 * @author Stefano Chizzolini
 * @see MainTaglet
 * @see Jada
 */
public abstract class PostTaglet extends JadaTaglet {
  /**
   * Returns the string representation of the tag on post-processing.
   *
   * @param tagValue
   *          Tag value.
   * @param tagStart
   *          Starting position of the tag.
   * @param tagEnd
   *          Ending position of the tag.
   * @param fileContent
   *          Content of the file where the tag is located.
   * @param filePath
   *          Tag location.
   * @return {@code null}, if rendering is postponed (in case post-processing conditions have not
   *         occurred yet; this will cause the file scanner to make another cycle across incomplete
   *         files until all are complete).
   */
  public abstract @Nullable String render(String tagValue, int tagStart, int tagEnd,
      String fileContent, Path filePath);

  /**
   * @return String representation of the tag as-is, in order to postpone its processing to the
   *         generated documentation.
   * @implSpec In case of override, implementers MUST delegate its result to this super method.
   * @implNote The tag is rendered as-is, since its actual resolution is delayed to
   *           {@linkplain #render(String, int, int, String, Path) post-processing}.
   */
  @Override
  public String toString(List<? extends DocTree> tags, Element element) {
    return "{@%s %s}".formatted(getName(), toValue(tags, element));
  }

  /**
   * Converts the tags to their textual value, used as post-processing argument.
   */
  protected String toValue(List<? extends DocTree> tags, Element element) {
    return requireNonNull(LangModels.text(tags.get(0)));
  }
}
