######### OPTIONS #############################################################
-d=\
Destination directory for output files.
--debug=\
Whether executing in debug mode.\n\
Useful to generate diagnostic data and preserve temporary files which would be\n\
cleaned up on normal execution.
-encoding=\
Source file encoding name.
--jada-dir=\
(repeatable) Resource directory for Jada doclet.\n\
Expected subdirectories:\n\
- attach: resources to attach to Javadoc output. Subdirectories:\n\
--- common: resources common to any output\n\
--- java%JAVA_VERSION%: resources bound to specific javadoc tool versions.\n\
Supported version identifiers: java11 (Java 11-16), java17 (Java 17+)\n\
- ext: script extensions, and extension-specific resources under respective\n\
subdirectories named after the corresponding extension (for example,\n\
"ext/JadaBiblio" for JadaBiblio extension)
--jada-doclet=\
Base doclet, that is Javadoc processor delegated by Jada doclet.\n\
One of the following values (either by component name or class):{0}\n\
DEFAULT: single doclet available (in case of multiple doclets, an\n\
exception is thrown).
--jada-exts=\
(incremental) Jada doclet extensions.\n\
One or more of the following values (either by component name or class; script\n\
extensions are NOT shown here):{0}\n\
DEFAULT: (none)
--jada-file-optimize-exclude=\
(incremental) Paths of files excluded from optimization.\n\
NOTE: This option is incremental, that is it can be repeated with a modifier\n\
prefix (+ or -) to, respectively, add or remove elements; without modifier, the\n\
collection is overridden.\n\
EXAMPLE 1: to exclude all javascripts, use:\n\
"*.js"\n\
EXAMPLE 2: to exclude files under "/my/package/" subdirectory and "/another/",\n\
use:\n\
"/my/package/,/another/"\n\
EXAMPLE 3: to add exclusions after another option occurrence, use:\n\
"+/my/package/,/another/"
--log-level=\
Displayed messages' threshold.\n\
DEFAULT: 'INFO'
