/*
  SPDX-FileCopyrightText: © 2025 Stefano Chizzolini and contributors

  SPDX-License-Identifier: LGPL-3.0-only

  This file (JadaFileProcess.java) is part of jada-core module in Jada project
  <https://github.com/pdfclown/jada>

  DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER. If you reuse (entirely or partially)
  this file, you MUST add your own copyright notice in a separate comment block above this file
  header, listing the main changes you applied to the original source.
 */
package org.pdfclown.jada.core.proc;

import static org.pdfclown.common.util.Conditions.requireType;

import org.pdfclown.jada.core.Jada;
import org.pdfclown.jada.core.JadaConfig;
import org.pdfclown.jada.core.JadaOperation;
import org.pdfclown.jada.core.system.SystemConfig;
import org.pdfclown.jada.core.system.proc.FileProcess;
import org.pdfclown.jada.core.system.proc.FileProcess.RunResult;

/**
 * File post-processing for Javadoc output.
 * <p>
 * Walks across the files generated by the doclet under {@linkplain JadaConfig#getOutputDirectory()
 * output directory}.
 * </p>
 *
 * @author Stefano Chizzolini
 */
public class JadaFileProcess extends FileProcess<JadaFileProcessor<?>>
    implements JadaOperation<RunResult> {
  @Override
  public JadaFileProcess addProcessor(JadaFileProcessor<?> processor) {
    /*
     * NOTE: Because of classpath boundaries imposed by the standard doclet between jada-core and
     * its extensions, the same type (for example `JadaFileProcessor`) has its definition separately
     * loaded by each module, causing binary incompatibilities; as a consequence, generic method
     * binding fails (`NoSuchMethodError` for `addProcessor(JadaFileProcessor)`), forcing us to
     * explicitly override this method.
     */
    return (JadaFileProcess) super.addProcessor(processor);
  }

  @Override
  public JadaConfig getConfig() {
    return (JadaConfig) super.getConfig();
  }

  @Override
  public Jada getJada() {
    return getConfig().getJada();
  }

  @Override
  public void init(SystemConfig config) {
    super.init(requireType(config, JadaConfig.class, "config"));

    getDirectories().add(getConfig().getOutputDirectory());
  }

  @Override
  public void term() {
    processors.forEach(($k, $v) -> $v.term());
  }
}
