/*
 PrismJS 1.30.0
 https://prismjs.com/download#themes=prism-tomorrow&languages=markup+css+clike+bash+bnf+ebnf+java&plugins=line-highlight

 @license MIT <https://opensource.org/licenses/MIT>
 @author Lea Verou <https://lea.verou.me>
 @namespace
 @public
*/
var _self="undefined"!==typeof window?window:"undefined"!==typeof WorkerGlobalScope&&self instanceof WorkerGlobalScope?self:{},Prism=function(h){function k(n,m,f,a){this.type=n;this.content=m;this.alias=f;this.length=(a||"").length|0}function u(n,m,f,a){n.lastIndex=m;(n=n.exec(f))&&a&&n[1]&&(a=n[1].length,n.index+=a,n[0]=n[0].slice(a));return n}function x(n,m,f,a,d,c){for(var g in f)if(f.hasOwnProperty(g)&&f[g]){var t=f[g];t=Array.isArray(t)?t:[t];for(var q=0;q<t.length;++q){if(c&&c.cause==g+","+
q)return;var l=t[q],p=l.inside,y=!!l.lookbehind,C=!!l.greedy,E=l.alias;if(C&&!l.pattern.global){var v=l.pattern.toString().match(/[imsuy]*$/)[0];l.pattern=RegExp(l.pattern.source,v+"g")}l=l.pattern||l;var r=a.next;for(v=d;r!==m.tail&&!(c&&v>=c.reach);v+=r.value.length,r=r.next){var A=r.value;if(m.length>n.length)return;if(!(A instanceof k)){var F=1;if(C){var w=u(l,v,n,y);if(!w||w.index>=n.length)break;var D=w.index;A=w.index+w[0].length;var B=v;for(B+=r.value.length;D>=B;)r=r.next,B+=r.value.length;
v=B-=r.value.length;if(r.value instanceof k)continue;for(D=r;D!==m.tail&&(B<A||"string"===typeof D.value);D=D.next)F++,B+=D.value.length;F--;A=n.slice(v,B);w.index-=v}else if(w=u(l,0,A,y),!w)continue;D=w.index;w=w[0];B=A.slice(0,D);D=A.slice(D+w.length);A=v+A.length;c&&A>c.reach&&(c.reach=A);r=r.prev;B&&(r=G(m,r,B),v+=B.length);B=m;for(var M=r,I=M.next,N=0;N<F&&I!==B.tail;N++)I=I.next;M.next=I;I.prev=M;B.length-=N;w=new k(g,p?b.tokenize(w,p):w,E,w);r=G(m,r,w);D&&G(m,r,D);1<F&&(F={cause:g+","+q,reach:A},
x(n,m,f,r.prev,v,F),c&&F.reach>c.reach&&(c.reach=F.reach))}}}}}function K(){var n={value:null,prev:null,next:null},m={value:null,prev:n,next:null};n.next=m;this.head=n;this.tail=m;this.length=0}function G(n,m,f){var a=m.next;f={value:f,prev:m,next:a};m.next=f;a.prev=f;n.length++;return f}function J(){b.manual||b.highlightAll()}var H=/(?:^|\s)lang(?:uage)?-([\w-]+)(?=\s|$)/i,L=0,e={},b={manual:h.Prism&&h.Prism.manual,disableWorkerMessageHandler:h.Prism&&h.Prism.disableWorkerMessageHandler,util:{encode:function f(m){return m instanceof
k?new k(m.type,f(m.content),m.alias):Array.isArray(m)?m.map(f):m.replace(/&/g,"\x26amp;").replace(/</g,"\x26lt;").replace(/\u00a0/g," ")},type:function(m){return Object.prototype.toString.call(m).slice(8,-1)},objId:function(m){m.__id||Object.defineProperty(m,"__id",{value:++L});return m.__id},clone:function d(f,a){a=a||{};switch(b.util.type(f)){case "Object":var c=b.util.objId(f);if(a[c])return a[c];var g={};a[c]=g;for(var t in f)f.hasOwnProperty(t)&&(g[t]=d(f[t],a));return g;case "Array":c=b.util.objId(f);
if(a[c])return a[c];g=[];a[c]=g;f.forEach(function(q,l){g[l]=d(q,a)});return g;default:return f}},getLanguage:function(f){for(;f;){var a=H.exec(f.className);if(a)return a[1].toLowerCase();f=f.parentElement}return"none"},setLanguage:function(f,a){f.className=f.className.replace(RegExp(H,"gi"),"");f.classList.add("language-"+a)},currentScript:function(){if("undefined"===typeof document)return null;if(document.currentScript&&"SCRIPT"===document.currentScript.tagName)return document.currentScript;try{throw Error();
}catch(c){var f=(/at [^(\r\n]*\((.*):[^:]+:[^:]+\)$/i.exec(c.stack)||[])[1];if(f){var a=document.getElementsByTagName("script"),d;for(d in a)if(a[d].src==f)return a[d]}return null}},isActive:function(f,a,d){for(var c="no-"+a;f;){var g=f.classList;if(g.contains(a))return!0;if(g.contains(c))return!1;f=f.parentElement}return!!d}},languages:{plain:e,plaintext:e,text:e,txt:e,extend:function(f,a){f=b.util.clone(b.languages[f]);for(var d in a)f[d]=a[d];return f},insertBefore:function(f,a,d,c){c=c||b.languages;
var g=c[f],t={},q;for(q in g)if(g.hasOwnProperty(q)){if(q==a)for(var l in d)d.hasOwnProperty(l)&&(t[l]=d[l]);d.hasOwnProperty(q)||(t[q]=g[q])}var p=c[f];c[f]=t;b.languages.DFS(b.languages,function(y,C){C===p&&y!=f&&(this[y]=t)});return t},DFS:function t(a,d,c,g){g=g||{};var q=b.util.objId,l;for(l in a)if(a.hasOwnProperty(l)){d.call(a,l,a[l],c||l);var p=a[l],y=b.util.type(p);"Object"!==y||g[q(p)]?"Array"!==y||g[q(p)]||(g[q(p)]=!0,t(p,d,l,g)):(g[q(p)]=!0,t(p,d,null,g))}}},plugins:{},highlightAll:function(a,
d){b.highlightAllUnder(document,a,d)},highlightAllUnder:function(a,d,c){a={callback:c,container:a,selector:'code[class*\x3d"language-"], [class*\x3d"language-"] code, code[class*\x3d"lang-"], [class*\x3d"lang-"] code'};b.hooks.run("before-highlightall",a);a.elements=Array.prototype.slice.apply(a.container.querySelectorAll(a.selector));b.hooks.run("before-all-elements-highlight",a);c=0;for(var g;g=a.elements[c++];)b.highlightElement(g,!0===d,a.callback)},highlightElement:function(a,d,c){function g(y){p.highlightedCode=
y;b.hooks.run("before-insert",p);p.element.innerHTML=p.highlightedCode;b.hooks.run("after-highlight",p);b.hooks.run("complete",p);c&&c.call(p.element)}var t=b.util.getLanguage(a),q=b.languages[t];b.util.setLanguage(a,t);var l=a.parentElement;l&&"pre"===l.nodeName.toLowerCase()&&b.util.setLanguage(l,t);var p={element:a,language:t,grammar:q,code:a.textContent};b.hooks.run("before-sanity-check",p);(l=p.element.parentElement)&&"pre"===l.nodeName.toLowerCase()&&!l.hasAttribute("tabindex")&&l.setAttribute("tabindex",
"0");p.code?(b.hooks.run("before-highlight",p),p.grammar?d&&h.Worker?(a=new Worker(b.filename),a.onmessage=function(y){g(y.data)},a.postMessage(JSON.stringify({language:p.language,code:p.code,immediateClose:!0}))):g(b.highlight(p.code,p.grammar,p.language)):g(b.util.encode(p.code))):(b.hooks.run("complete",p),c&&c.call(p.element))},highlight:function(a,d,c){a={code:a,grammar:d,language:c};b.hooks.run("before-tokenize",a);if(!a.grammar)throw Error('The language "'+a.language+'" has no grammar.');a.tokens=
b.tokenize(a.code,a.grammar);b.hooks.run("after-tokenize",a);return k.stringify(b.util.encode(a.tokens),a.language)},tokenize:function(a,d){var c=d.rest;if(c){for(var g in c)d[g]=c[g];delete d.rest}c=new K;G(c,c.head,a);x(a,c,d,c.head,0);a=[];for(d=c.head.next;d!==c.tail;)a.push(d.value),d=d.next;return a},hooks:{all:{},add:function(a,d){var c=b.hooks.all;c[a]=c[a]||[];c[a].push(d)},run:function(a,d){if((a=b.hooks.all[a])&&a.length)for(var c=0,g;g=a[c++];)g(d)}},Token:k};h.Prism=b;k.stringify=function g(d,
c){if("string"==typeof d)return d;if(Array.isArray(d)){var t="";d.forEach(function(p){t+=g(p,c)});return t}var q={type:d.type,content:g(d.content,c),tag:"span",classes:["token",d.type],attributes:{},language:c};(d=d.alias)&&(Array.isArray(d)?Array.prototype.push.apply(q.classes,d):q.classes.push(d));b.hooks.run("wrap",q);d="";for(var l in q.attributes)d+=" "+l+'\x3d"'+(q.attributes[l]||"").replace(/"/g,"\x26quot;")+'"';return"\x3c"+q.tag+' class\x3d"'+q.classes.join(" ")+'"'+d+"\x3e"+q.content+"\x3c/"+
q.tag+"\x3e"};if(!h.document){if(!h.addEventListener)return b;b.disableWorkerMessageHandler||h.addEventListener("message",function(d){d=JSON.parse(d.data);var c=d.language,g=d.immediateClose;h.postMessage(b.highlight(d.code,b.languages[c],c));g&&h.close()},!1);return b}if(e=b.util.currentScript())b.filename=e.src,e.hasAttribute("data-manual")&&(b.manual=!0);if(!b.manual){var z=document.readyState;"loading"===z||"interactive"===z&&e&&e.defer?document.addEventListener("DOMContentLoaded",J):window.requestAnimationFrame?
window.requestAnimationFrame(J):window.setTimeout(J,16)}return b}(_self);"undefined"!==typeof module&&module.exports&&(module.exports=Prism);"undefined"!==typeof global&&(global.Prism=Prism);
Prism.languages.markup={comment:{pattern:/\x3c!--(?:(?!\x3c!--)[\s\S])*?--\x3e/,greedy:!0},prolog:{pattern:/<\?[\s\S]+?\?>/,greedy:!0},doctype:{pattern:/<!DOCTYPE(?:[^>"'[\]]|"[^"]*"|'[^']*')+(?:\[(?:[^<"'\]]|"[^"]*"|'[^']*'|<(?!!--)|\x3c!--(?:[^-]|-(?!->))*--\x3e)*\]\s*)?>/i,greedy:!0,inside:{"internal-subset":{pattern:/(^[^\[]*\[)[\s\S]+(?=\]>$)/,lookbehind:!0,greedy:!0,inside:null},string:{pattern:/"[^"]*"|'[^']*'/,greedy:!0},punctuation:/^<!|>$|[[\]]/,"doctype-tag":/^DOCTYPE/i,name:/[^\s<>'"]+/}},
cdata:{pattern:/<!\[CDATA\[[\s\S]*?\]\]>/i,greedy:!0},tag:{pattern:/<\/?(?!\d)[^\s>\/=$<%]+(?:\s(?:\s*[^\s>\/=]+(?:\s*=\s*(?:"[^"]*"|'[^']*'|[^\s'">=]+(?=[\s>]))|(?=[\s/>])))+)?\s*\/?>/,greedy:!0,inside:{tag:{pattern:/^<\/?[^\s>\/]+/,inside:{punctuation:/^<\/?/,namespace:/^[^\s>\/:]+:/}},"special-attr":[],"attr-value":{pattern:/=\s*(?:"[^"]*"|'[^']*'|[^\s'">=]+)/,inside:{punctuation:[{pattern:/^=/,alias:"attr-equals"},{pattern:/^(\s*)["']|["']$/,lookbehind:!0}]}},punctuation:/\/?>/,"attr-name":{pattern:/[^\s>\/]+/,
inside:{namespace:/^[^\s>\/:]+:/}}}},entity:[{pattern:/&[\da-z]{1,8};/i,alias:"named-entity"},/&#x?[\da-f]{1,8};/i]};Prism.languages.markup.tag.inside["attr-value"].inside.entity=Prism.languages.markup.entity;Prism.languages.markup.doctype.inside["internal-subset"].inside=Prism.languages.markup;Prism.hooks.add("wrap",function(h){"entity"===h.type&&(h.attributes.title=h.content.replace(/&amp;/,"\x26"))});
Object.defineProperty(Prism.languages.markup.tag,"addInlined",{value:function(h,k){var u={};u["language-"+k]={pattern:/(^<!\[CDATA\[)[\s\S]+?(?=\]\]>$)/i,lookbehind:!0,inside:Prism.languages[k]};u.cdata=/^<!\[CDATA\[|\]\]>$/i;u={"included-cdata":{pattern:/<!\[CDATA\[[\s\S]*?\]\]>/i,inside:u}};u["language-"+k]={pattern:/[\s\S]+/,inside:Prism.languages[k]};k={};k[h]={pattern:RegExp(/(<__[^>]*>)(?:<!\[CDATA\[(?:[^\]]|\](?!\]>))*\]\]>|(?!<!\[CDATA\[)[\s\S])*?(?=<\/__>)/.source.replace(/__/g,function(){return h}),
"i"),lookbehind:!0,greedy:!0,inside:u};Prism.languages.insertBefore("markup","cdata",k)}});
Object.defineProperty(Prism.languages.markup.tag,"addAttribute",{value:function(h,k){Prism.languages.markup.tag.inside["special-attr"].push({pattern:RegExp(/(^|["'\s])/.source+"(?:"+h+")"+/\s*=\s*(?:"[^"]*"|'[^']*'|[^\s'">=]+(?=[\s>]))/.source,"i"),lookbehind:!0,inside:{"attr-name":/^[^\s=]+/,"attr-value":{pattern:/=[\s\S]+/,inside:{value:{pattern:/(^=\s*(["']|(?!["'])))\S[\s\S]*(?=\2$)/,lookbehind:!0,alias:[k,"language-"+k],inside:Prism.languages[k]},punctuation:[{pattern:/^=/,alias:"attr-equals"},
/"|'/]}}}})}});Prism.languages.html=Prism.languages.markup;Prism.languages.mathml=Prism.languages.markup;Prism.languages.svg=Prism.languages.markup;Prism.languages.xml=Prism.languages.extend("markup",{});Prism.languages.ssml=Prism.languages.xml;Prism.languages.atom=Prism.languages.xml;Prism.languages.rss=Prism.languages.xml;
(function(h){var k=/(?:"(?:\\(?:\r\n|[\s\S])|[^"\\\r\n])*"|'(?:\\(?:\r\n|[\s\S])|[^'\\\r\n])*')/;h.languages.css={comment:/\/\*[\s\S]*?\*\//,atrule:{pattern:RegExp("@[\\w-](?:"+/[^;{\s"']|\s+(?!\s)/.source+"|"+k.source+")*?"+/(?:;|(?=\s*\{))/.source),inside:{rule:/^@[\w-]+/,"selector-function-argument":{pattern:/(\bselector\s*\(\s*(?![\s)]))(?:[^()\s]|\s+(?![\s)])|\((?:[^()]|\([^()]*\))*\))+(?=\s*\))/,lookbehind:!0,alias:"selector"},keyword:{pattern:/(^|[^\w-])(?:and|not|only|or)(?![\w-])/,lookbehind:!0}}},
url:{pattern:RegExp("\\burl\\((?:"+k.source+"|"+/(?:[^\\\r\n()"']|\\[\s\S])*/.source+")\\)","i"),greedy:!0,inside:{"function":/^url/i,punctuation:/^\(|\)$/,string:{pattern:RegExp("^"+k.source+"$"),alias:"url"}}},selector:{pattern:RegExp("(^|[{}\\s])[^{}\\s](?:[^{};\"'\\s]|\\s+(?![\\s{])|"+k.source+")*(?\x3d\\s*\\{)"),lookbehind:!0},string:{pattern:k,greedy:!0},property:{pattern:/(^|[^-\w\xA0-\uFFFF])(?!\s)[-_a-z\xA0-\uFFFF](?:(?!\s)[-\w\xA0-\uFFFF])*(?=\s*:)/i,lookbehind:!0},important:/!important\b/i,
"function":{pattern:/(^|[^-a-z0-9])[-a-z0-9]+(?=\()/i,lookbehind:!0},punctuation:/[(){};:,]/};h.languages.css.atrule.inside.rest=h.languages.css;if(h=h.languages.markup)h.tag.addInlined("style","css"),h.tag.addAttribute("style","css")})(Prism);
Prism.languages.clike={comment:[{pattern:/(^|[^\\])\/\*[\s\S]*?(?:\*\/|$)/,lookbehind:!0,greedy:!0},{pattern:/(^|[^\\:])\/\/.*/,lookbehind:!0,greedy:!0}],string:{pattern:/(["'])(?:\\(?:\r\n|[\s\S])|(?!\1)[^\\\r\n])*\1/,greedy:!0},"class-name":{pattern:/(\b(?:class|extends|implements|instanceof|interface|new|trait)\s+|\bcatch\s+\()[\w.\\]+/i,lookbehind:!0,inside:{punctuation:/[.\\]/}},keyword:/\b(?:break|catch|continue|do|else|finally|for|function|if|in|instanceof|new|null|return|throw|try|while)\b/,
"boolean":/\b(?:false|true)\b/,"function":/\b\w+(?=\()/,number:/\b0x[\da-f]+\b|(?:\b\d+(?:\.\d*)?|\B\.\d+)(?:e[+-]?\d+)?/i,operator:/[<>]=?|[!=]=?=?|--?|\+\+?|&&?|\|\|?|[?*/~^%]/,punctuation:/[{}[\];(),.:]/};
(function(h){var k={pattern:/(^(["']?)\w+\2)[ \t]+\S.*/,lookbehind:!0,alias:"punctuation",inside:null},u={bash:k,environment:{pattern:RegExp("\\$\\b(?:BASH|BASHOPTS|BASH_ALIASES|BASH_ARGC|BASH_ARGV|BASH_CMDS|BASH_COMPLETION_COMPAT_DIR|BASH_LINENO|BASH_REMATCH|BASH_SOURCE|BASH_VERSINFO|BASH_VERSION|COLORTERM|COLUMNS|COMP_WORDBREAKS|DBUS_SESSION_BUS_ADDRESS|DEFAULTS_PATH|DESKTOP_SESSION|DIRSTACK|DISPLAY|EUID|GDMSESSION|GDM_LANG|GNOME_KEYRING_CONTROL|GNOME_KEYRING_PID|GPG_AGENT_INFO|GROUPS|HISTCONTROL|HISTFILE|HISTFILESIZE|HISTSIZE|HOME|HOSTNAME|HOSTTYPE|IFS|INSTANCE|JOB|LANG|LANGUAGE|LC_ADDRESS|LC_ALL|LC_IDENTIFICATION|LC_MEASUREMENT|LC_MONETARY|LC_NAME|LC_NUMERIC|LC_PAPER|LC_TELEPHONE|LC_TIME|LESSCLOSE|LESSOPEN|LINES|LOGNAME|LS_COLORS|MACHTYPE|MAILCHECK|MANDATORY_PATH|NO_AT_BRIDGE|OLDPWD|OPTERR|OPTIND|ORBIT_SOCKETDIR|OSTYPE|PAPERSIZE|PATH|PIPESTATUS|PPID|PS1|PS2|PS3|PS4|PWD|RANDOM|REPLY|SECONDS|SELINUX_INIT|SESSION|SESSIONTYPE|SESSION_MANAGER|SHELL|SHELLOPTS|SHLVL|SSH_AUTH_SOCK|TERM|UID|UPSTART_EVENTS|UPSTART_INSTANCE|UPSTART_JOB|UPSTART_SESSION|USER|WINDOWID|XAUTHORITY|XDG_CONFIG_DIRS|XDG_CURRENT_DESKTOP|XDG_DATA_DIRS|XDG_GREETER_DATA_DIR|XDG_MENU_PREFIX|XDG_RUNTIME_DIR|XDG_SEAT|XDG_SEAT_PATH|XDG_SESSION_DESKTOP|XDG_SESSION_ID|XDG_SESSION_PATH|XDG_SESSION_TYPE|XDG_VTNR|XMODIFIERS)\\b"),alias:"constant"},
variable:[{pattern:/\$?\(\([\s\S]+?\)\)/,greedy:!0,inside:{variable:[{pattern:/(^\$\(\([\s\S]+)\)\)/,lookbehind:!0},/^\$\(\(/],number:/\b0x[\dA-Fa-f]+\b|(?:\b\d+(?:\.\d*)?|\B\.\d+)(?:[Ee]-?\d+)?/,operator:/--|\+\+|\*\*=?|<<=?|>>=?|&&|\|\||[=!+\-*/%<>^&|]=?|[?~:]/,punctuation:/\(\(?|\)\)?|,|;/}},{pattern:/\$\((?:\([^)]+\)|[^()])+\)|`[^`]+`/,greedy:!0,inside:{variable:/^\$\(|^`|\)$|`$/}},{pattern:/\$\{[^}]+\}/,greedy:!0,inside:{operator:/:[-=?+]?|[!\/]|##?|%%?|\^\^?|,,?/,punctuation:/[\[\]]/,environment:{pattern:RegExp("(\\{)\\b(?:BASH|BASHOPTS|BASH_ALIASES|BASH_ARGC|BASH_ARGV|BASH_CMDS|BASH_COMPLETION_COMPAT_DIR|BASH_LINENO|BASH_REMATCH|BASH_SOURCE|BASH_VERSINFO|BASH_VERSION|COLORTERM|COLUMNS|COMP_WORDBREAKS|DBUS_SESSION_BUS_ADDRESS|DEFAULTS_PATH|DESKTOP_SESSION|DIRSTACK|DISPLAY|EUID|GDMSESSION|GDM_LANG|GNOME_KEYRING_CONTROL|GNOME_KEYRING_PID|GPG_AGENT_INFO|GROUPS|HISTCONTROL|HISTFILE|HISTFILESIZE|HISTSIZE|HOME|HOSTNAME|HOSTTYPE|IFS|INSTANCE|JOB|LANG|LANGUAGE|LC_ADDRESS|LC_ALL|LC_IDENTIFICATION|LC_MEASUREMENT|LC_MONETARY|LC_NAME|LC_NUMERIC|LC_PAPER|LC_TELEPHONE|LC_TIME|LESSCLOSE|LESSOPEN|LINES|LOGNAME|LS_COLORS|MACHTYPE|MAILCHECK|MANDATORY_PATH|NO_AT_BRIDGE|OLDPWD|OPTERR|OPTIND|ORBIT_SOCKETDIR|OSTYPE|PAPERSIZE|PATH|PIPESTATUS|PPID|PS1|PS2|PS3|PS4|PWD|RANDOM|REPLY|SECONDS|SELINUX_INIT|SESSION|SESSIONTYPE|SESSION_MANAGER|SHELL|SHELLOPTS|SHLVL|SSH_AUTH_SOCK|TERM|UID|UPSTART_EVENTS|UPSTART_INSTANCE|UPSTART_JOB|UPSTART_SESSION|USER|WINDOWID|XAUTHORITY|XDG_CONFIG_DIRS|XDG_CURRENT_DESKTOP|XDG_DATA_DIRS|XDG_GREETER_DATA_DIR|XDG_MENU_PREFIX|XDG_RUNTIME_DIR|XDG_SEAT|XDG_SEAT_PATH|XDG_SESSION_DESKTOP|XDG_SESSION_ID|XDG_SESSION_PATH|XDG_SESSION_TYPE|XDG_VTNR|XMODIFIERS)\\b"),
lookbehind:!0,alias:"constant"}}},/\$(?:\w+|[#?*!@$])/],entity:/\\(?:[abceEfnrtv\\"]|O?[0-7]{1,3}|U[0-9a-fA-F]{8}|u[0-9a-fA-F]{4}|x[0-9a-fA-F]{1,2})/};h.languages.bash={shebang:{pattern:/^#!\s*\/.*/,alias:"important"},comment:{pattern:/(^|[^"{\\$])#.*/,lookbehind:!0},"function-name":[{pattern:/(\bfunction\s+)[\w-]+(?=(?:\s*\(?:\s*\))?\s*\{)/,lookbehind:!0,alias:"function"},{pattern:/\b[\w-]+(?=\s*\(\s*\)\s*\{)/,alias:"function"}],"for-or-select":{pattern:/(\b(?:for|select)\s+)\w+(?=\s+in\s)/,alias:"variable",
lookbehind:!0},"assign-left":{pattern:/(^|[\s;|&]|[<>]\()\w+(?:\.\w+)*(?=\+?=)/,inside:{environment:{pattern:RegExp("(^|[\\s;|\x26]|[\x3c\x3e]\\()\\b(?:BASH|BASHOPTS|BASH_ALIASES|BASH_ARGC|BASH_ARGV|BASH_CMDS|BASH_COMPLETION_COMPAT_DIR|BASH_LINENO|BASH_REMATCH|BASH_SOURCE|BASH_VERSINFO|BASH_VERSION|COLORTERM|COLUMNS|COMP_WORDBREAKS|DBUS_SESSION_BUS_ADDRESS|DEFAULTS_PATH|DESKTOP_SESSION|DIRSTACK|DISPLAY|EUID|GDMSESSION|GDM_LANG|GNOME_KEYRING_CONTROL|GNOME_KEYRING_PID|GPG_AGENT_INFO|GROUPS|HISTCONTROL|HISTFILE|HISTFILESIZE|HISTSIZE|HOME|HOSTNAME|HOSTTYPE|IFS|INSTANCE|JOB|LANG|LANGUAGE|LC_ADDRESS|LC_ALL|LC_IDENTIFICATION|LC_MEASUREMENT|LC_MONETARY|LC_NAME|LC_NUMERIC|LC_PAPER|LC_TELEPHONE|LC_TIME|LESSCLOSE|LESSOPEN|LINES|LOGNAME|LS_COLORS|MACHTYPE|MAILCHECK|MANDATORY_PATH|NO_AT_BRIDGE|OLDPWD|OPTERR|OPTIND|ORBIT_SOCKETDIR|OSTYPE|PAPERSIZE|PATH|PIPESTATUS|PPID|PS1|PS2|PS3|PS4|PWD|RANDOM|REPLY|SECONDS|SELINUX_INIT|SESSION|SESSIONTYPE|SESSION_MANAGER|SHELL|SHELLOPTS|SHLVL|SSH_AUTH_SOCK|TERM|UID|UPSTART_EVENTS|UPSTART_INSTANCE|UPSTART_JOB|UPSTART_SESSION|USER|WINDOWID|XAUTHORITY|XDG_CONFIG_DIRS|XDG_CURRENT_DESKTOP|XDG_DATA_DIRS|XDG_GREETER_DATA_DIR|XDG_MENU_PREFIX|XDG_RUNTIME_DIR|XDG_SEAT|XDG_SEAT_PATH|XDG_SESSION_DESKTOP|XDG_SESSION_ID|XDG_SESSION_PATH|XDG_SESSION_TYPE|XDG_VTNR|XMODIFIERS)\\b"),
lookbehind:!0,alias:"constant"}},alias:"variable",lookbehind:!0},parameter:{pattern:/(^|\s)-{1,2}(?:\w+:[+-]?)?\w+(?:\.\w+)*(?=[=\s]|$)/,alias:"variable",lookbehind:!0},string:[{pattern:/((?:^|[^<])<<-?\s*)(\w+)\s[\s\S]*?(?:\r?\n|\r)\2/,lookbehind:!0,greedy:!0,inside:u},{pattern:/((?:^|[^<])<<-?\s*)(["'])(\w+)\2\s[\s\S]*?(?:\r?\n|\r)\3/,lookbehind:!0,greedy:!0,inside:{bash:k}},{pattern:/(^|[^\\](?:\\\\)*)"(?:\\[\s\S]|\$\([^)]+\)|\$(?!\()|`[^`]+`|[^"\\`$])*"/,lookbehind:!0,greedy:!0,inside:u},{pattern:/(^|[^$\\])'[^']*'/,
lookbehind:!0,greedy:!0},{pattern:/\$'(?:[^'\\]|\\[\s\S])*'/,greedy:!0,inside:{entity:u.entity}}],environment:{pattern:RegExp("\\$?\\b(?:BASH|BASHOPTS|BASH_ALIASES|BASH_ARGC|BASH_ARGV|BASH_CMDS|BASH_COMPLETION_COMPAT_DIR|BASH_LINENO|BASH_REMATCH|BASH_SOURCE|BASH_VERSINFO|BASH_VERSION|COLORTERM|COLUMNS|COMP_WORDBREAKS|DBUS_SESSION_BUS_ADDRESS|DEFAULTS_PATH|DESKTOP_SESSION|DIRSTACK|DISPLAY|EUID|GDMSESSION|GDM_LANG|GNOME_KEYRING_CONTROL|GNOME_KEYRING_PID|GPG_AGENT_INFO|GROUPS|HISTCONTROL|HISTFILE|HISTFILESIZE|HISTSIZE|HOME|HOSTNAME|HOSTTYPE|IFS|INSTANCE|JOB|LANG|LANGUAGE|LC_ADDRESS|LC_ALL|LC_IDENTIFICATION|LC_MEASUREMENT|LC_MONETARY|LC_NAME|LC_NUMERIC|LC_PAPER|LC_TELEPHONE|LC_TIME|LESSCLOSE|LESSOPEN|LINES|LOGNAME|LS_COLORS|MACHTYPE|MAILCHECK|MANDATORY_PATH|NO_AT_BRIDGE|OLDPWD|OPTERR|OPTIND|ORBIT_SOCKETDIR|OSTYPE|PAPERSIZE|PATH|PIPESTATUS|PPID|PS1|PS2|PS3|PS4|PWD|RANDOM|REPLY|SECONDS|SELINUX_INIT|SESSION|SESSIONTYPE|SESSION_MANAGER|SHELL|SHELLOPTS|SHLVL|SSH_AUTH_SOCK|TERM|UID|UPSTART_EVENTS|UPSTART_INSTANCE|UPSTART_JOB|UPSTART_SESSION|USER|WINDOWID|XAUTHORITY|XDG_CONFIG_DIRS|XDG_CURRENT_DESKTOP|XDG_DATA_DIRS|XDG_GREETER_DATA_DIR|XDG_MENU_PREFIX|XDG_RUNTIME_DIR|XDG_SEAT|XDG_SEAT_PATH|XDG_SESSION_DESKTOP|XDG_SESSION_ID|XDG_SESSION_PATH|XDG_SESSION_TYPE|XDG_VTNR|XMODIFIERS)\\b"),
alias:"constant"},variable:u.variable,"function":{pattern:/(^|[\s;|&]|[<>]\()(?:add|apropos|apt|apt-cache|apt-get|aptitude|aspell|automysqlbackup|awk|basename|bash|bc|bconsole|bg|bzip2|cal|cargo|cat|cfdisk|chgrp|chkconfig|chmod|chown|chroot|cksum|clear|cmp|column|comm|composer|cp|cron|crontab|csplit|curl|cut|date|dc|dd|ddrescue|debootstrap|df|diff|diff3|dig|dir|dircolors|dirname|dirs|dmesg|docker|docker-compose|du|egrep|eject|env|ethtool|expand|expect|expr|fdformat|fdisk|fg|fgrep|file|find|fmt|fold|format|free|fsck|ftp|fuser|gawk|git|gparted|grep|groupadd|groupdel|groupmod|groups|grub-mkconfig|gzip|halt|head|hg|history|host|hostname|htop|iconv|id|ifconfig|ifdown|ifup|import|install|ip|java|jobs|join|kill|killall|less|link|ln|locate|logname|logrotate|look|lpc|lpr|lprint|lprintd|lprintq|lprm|ls|lsof|lynx|make|man|mc|mdadm|mkconfig|mkdir|mke2fs|mkfifo|mkfs|mkisofs|mknod|mkswap|mmv|more|most|mount|mtools|mtr|mutt|mv|nano|nc|netstat|nice|nl|node|nohup|notify-send|npm|nslookup|op|open|parted|passwd|paste|pathchk|ping|pkill|pnpm|podman|podman-compose|popd|pr|printcap|printenv|ps|pushd|pv|quota|quotacheck|quotactl|ram|rar|rcp|reboot|remsync|rename|renice|rev|rm|rmdir|rpm|rsync|scp|screen|sdiff|sed|sendmail|seq|service|sftp|sh|shellcheck|shuf|shutdown|sleep|slocate|sort|split|ssh|stat|strace|su|sudo|sum|suspend|swapon|sync|sysctl|tac|tail|tar|tee|time|timeout|top|touch|tr|traceroute|tsort|tty|umount|uname|unexpand|uniq|units|unrar|unshar|unzip|update-grub|uptime|useradd|userdel|usermod|users|uudecode|uuencode|v|vcpkg|vdir|vi|vim|virsh|vmstat|wait|watch|wc|wget|whereis|which|who|whoami|write|xargs|xdg-open|yarn|yes|zenity|zip|zsh|zypper)(?=$|[)\s;|&])/,
lookbehind:!0},keyword:{pattern:/(^|[\s;|&]|[<>]\()(?:case|do|done|elif|else|esac|fi|for|function|if|in|select|then|until|while)(?=$|[)\s;|&])/,lookbehind:!0},builtin:{pattern:/(^|[\s;|&]|[<>]\()(?:\.|:|alias|bind|break|builtin|caller|cd|command|continue|declare|echo|enable|eval|exec|exit|export|getopts|hash|help|let|local|logout|mapfile|printf|pwd|read|readarray|readonly|return|set|shift|shopt|source|test|times|trap|type|typeset|ulimit|umask|unalias|unset)(?=$|[)\s;|&])/,lookbehind:!0,alias:"class-name"},
"boolean":{pattern:/(^|[\s;|&]|[<>]\()(?:false|true)(?=$|[)\s;|&])/,lookbehind:!0},"file-descriptor":{pattern:/\B&\d\b/,alias:"important"},operator:{pattern:/\d?<>|>\||\+=|=[=~]?|!=?|<<[<-]?|[&\d]?>>|\d[<>]&?|[<>][&=]?|&[>&]?|\|[&|]?/,inside:{"file-descriptor":{pattern:/^\d/,alias:"important"}}},punctuation:/\$?\(\(?|\)\)?|\.\.|[{}[\];\\]/,number:{pattern:/(^|\s)(?:[1-9]\d*|0)(?:[.,]\d+)?\b/,lookbehind:!0}};k.inside=h.languages.bash;k="comment function-name for-or-select assign-left parameter string environment function keyword builtin boolean file-descriptor operator punctuation number".split(" ");
u=u.variable[1].inside;for(var x=0;x<k.length;x++)u[k[x]]=h.languages.bash[k[x]];h.languages.sh=h.languages.bash;h.languages.shell=h.languages.bash})(Prism);Prism.languages.bnf={string:{pattern:/"[^\r\n"]*"|'[^\r\n']*'/},definition:{pattern:/<[^<>\r\n\t]+>(?=\s*::=)/,alias:["rule","keyword"],inside:{punctuation:/^<|>$/}},rule:{pattern:/<[^<>\r\n\t]+>/,inside:{punctuation:/^<|>$/}},operator:/::=|[|()[\]{}*+?]|\.{3}/};Prism.languages.rbnf=Prism.languages.bnf;
Prism.languages.ebnf={comment:/\(\*[\s\S]*?\*\)/,string:{pattern:/"[^"\r\n]*"|'[^'\r\n]*'/,greedy:!0},special:{pattern:/\?[^?\r\n]*\?/,greedy:!0,alias:"class-name"},definition:{pattern:/^([\t ]*)[a-z]\w*(?:[ \t]+[a-z]\w*)*(?=\s*=)/im,lookbehind:!0,alias:["rule","keyword"]},rule:/\b[a-z]\w*(?:[ \t]+[a-z]\w*)*\b/i,punctuation:/\([:/]|[:/]\)|[.,;()[\]{}]/,operator:/[-=|*/!]/};
(function(h){var k=/\b(?:abstract|assert|boolean|break|byte|case|catch|char|class|const|continue|default|do|double|else|enum|exports|extends|final|finally|float|for|goto|if|implements|import|instanceof|int|interface|long|module|native|new|non-sealed|null|open|opens|package|permits|private|protected|provides|public|record(?!\s*[(){}[\]<>=%~.:,;?+\-*/&|^])|requires|return|sealed|short|static|strictfp|super|switch|synchronized|this|throw|throws|to|transient|transitive|try|uses|var|void|volatile|while|with|yield)\b/,u=
/(?:[a-z]\w*\s*\.\s*)*(?:[A-Z]\w*\s*\.\s*)*/.source,x={pattern:RegExp(/(^|[^\w.])/.source+u+/[A-Z](?:[\d_A-Z]*[a-z]\w*)?\b/.source),lookbehind:!0,inside:{namespace:{pattern:/^[a-z]\w*(?:\s*\.\s*[a-z]\w*)*(?:\s*\.)?/,inside:{punctuation:/\./}},punctuation:/\./}};h.languages.java=h.languages.extend("clike",{string:{pattern:/(^|[^\\])"(?:\\.|[^"\\\r\n])*"/,lookbehind:!0,greedy:!0},"class-name":[x,{pattern:RegExp(/(^|[^\w.])/.source+u+/[A-Z]\w*(?=\s+\w+\s*[;,=()]|\s*(?:\[[\s,]*\]\s*)?::\s*new\b)/.source),
lookbehind:!0,inside:x.inside},{pattern:RegExp(/(\b(?:class|enum|extends|implements|instanceof|interface|new|record|throws)\s+)/.source+u+/[A-Z]\w*\b/.source),lookbehind:!0,inside:x.inside}],keyword:k,"function":[h.languages.clike.function,{pattern:/(::\s*)[a-z_]\w*/,lookbehind:!0}],number:/\b0b[01][01_]*L?\b|\b0x(?:\.[\da-f_p+-]+|[\da-f_]+(?:\.[\da-f_p+-]+)?)\b|(?:\b\d[\d_]*(?:\.[\d_]*)?|\B\.\d[\d_]*)(?:e[+-]?\d[\d_]*)?[dfl]?/i,operator:{pattern:/(^|[^.])(?:<<=?|>>>?=?|->|--|\+\+|&&|\|\||::|[?:~]|[-+*/%&|^!=<>]=?)/m,
lookbehind:!0},constant:/\b[A-Z][A-Z_\d]+\b/});h.languages.insertBefore("java","string",{"triple-quoted-string":{pattern:/"""[ \t]*[\r\n](?:(?:"|"")?(?:\\.|[^"\\]))*"""/,greedy:!0,alias:"string"},"char":{pattern:/'(?:\\.|[^'\\\r\n]){1,6}'/,greedy:!0}});h.languages.insertBefore("java","class-name",{annotation:{pattern:/(^|[^.])@\w+(?:\s*\.\s*\w+)*/,lookbehind:!0,alias:"punctuation"},generics:{pattern:/<(?:[\w\s,.?]|&(?!&)|<(?:[\w\s,.?]|&(?!&)|<(?:[\w\s,.?]|&(?!&)|<(?:[\w\s,.?]|&(?!&))*>)*>)*>)*>/,
inside:{"class-name":x,keyword:k,punctuation:/[<>(),.:]/,operator:/[?&|]/}},"import":[{pattern:RegExp(/(\bimport\s+)/.source+u+/(?:[A-Z]\w*|\*)(?=\s*;)/.source),lookbehind:!0,inside:{namespace:x.inside.namespace,punctuation:/\./,operator:/\*/,"class-name":/\w+/}},{pattern:RegExp(/(\bimport\s+static\s+)/.source+u+/(?:\w+|\*)(?=\s*;)/.source),lookbehind:!0,alias:"static",inside:{namespace:x.inside.namespace,"static":/\b\w+$/,punctuation:/\./,operator:/\*/,"class-name":/\w+/}}],namespace:{pattern:RegExp(/(\b(?:exports|import(?:\s+static)?|module|open|opens|package|provides|requires|to|transitive|uses|with)\s+)(?!<keyword>)[a-z]\w*(?:\.[a-z]\w*)*\.?/.source.replace(/<keyword>/g,
function(){return k.source})),lookbehind:!0,inside:{punctuation:/\./}}})})(Prism);
(function(){function h(e,b){return Array.prototype.slice.call((b||document).querySelectorAll(e))}function k(e){e()}function u(e,b){function z(m){return+m.substr(0,m.length-2)}e=getComputedStyle(e);var n=getComputedStyle(b);return b.offsetTop+z(n.borderTopWidth)+z(n.paddingTop)-z(e.paddingTop)}function x(e){return e&&/pre/i.test(e.nodeName)?e.hasAttribute("data-line")||e.id&&Prism.util.isActive(e,"linkable-line-numbers")?!0:!1:!1}function K(){var e=location.hash.slice(1);h(".temporary.line-highlight").forEach(function(z){z.parentNode.removeChild(z)});
var b=(e.match(/\.([\d,-]+)$/)||[,""])[1];b&&!document.getElementById(e)&&(e=e.slice(0,e.lastIndexOf(".")),e=document.getElementById(e))&&(e.hasAttribute("data-line")||e.setAttribute("data-line",""),Prism.plugins.lineHighlight.highlightLines(e,b,"temporary ")(),H&&document.querySelector(".temporary.line-highlight").scrollIntoView())}if("undefined"!==typeof Prism&&"undefined"!==typeof document&&document.querySelector){var G=/\n(?!$)/g,J=function(){var e;return function(){if("undefined"===typeof e){var b=
document.createElement("div");b.style.fontSize="13px";b.style.lineHeight="1.5";b.style.padding="0";b.style.border="0";b.innerHTML="\x26nbsp;\x3cbr /\x3e\x26nbsp;";document.body.appendChild(b);e=38===b.offsetHeight;document.body.removeChild(b)}return e}}(),H=!0;Prism.plugins.lineHighlight={highlightLines:function(e,b,z){b="string"===typeof b?b:e.getAttribute("data-line")||"";b=b.replace(/\s+/g,"").split(",").filter(Boolean);var n=+e.getAttribute("data-line-offset")||0,m=(J()?parseInt:parseFloat)(getComputedStyle(e).lineHeight),
f=Prism.util.isActive(e,"line-numbers"),a=e.querySelector("code"),d=f?e:a||e,c=[],g=a.textContent.match(G),t=g?g.length+1:1,q=a&&d!=a?u(e,a):0;b.forEach(function(y){var C=y.split("-"),E=+C[0],v=+C[1]||E;v=Math.min(t+n,v);if(!(v<E)){var r=e.querySelector('.line-highlight[data-range\x3d"'+y+'"]')||document.createElement("div");c.push(function(){r.setAttribute("aria-hidden","true");r.setAttribute("data-range",y);r.className=(z||"")+" line-highlight"});if(f&&Prism.plugins.lineNumbers){C=Prism.plugins.lineNumbers.getLine(e,
E);var A=Prism.plugins.lineNumbers.getLine(e,v);if(C){var F=C.offsetTop+q+"px";c.push(function(){r.style.top=F})}if(A){var w=A.offsetTop-C.offsetTop+A.offsetHeight+"px";c.push(function(){r.style.height=w})}}else c.push(function(){r.setAttribute("data-start",String(E));v>E&&r.setAttribute("data-end",String(v));r.style.top=(E-n-1)*m+q+"px";r.textContent=Array(v-E+2).join(" \n")});c.push(function(){r.style.width=e.scrollWidth+"px"});c.push(function(){d.appendChild(r)})}});var l=e.id;if(f&&Prism.util.isActive(e,
"linkable-line-numbers")&&l){e.classList.contains("linkable-line-numbers")||c.push(function(){e.classList.add("linkable-line-numbers")});var p=parseInt(e.getAttribute("data-start")||"1");h(".line-numbers-rows \x3e span",e).forEach(function(y,C){var E=C+p;y.onclick=function(){var v=l+"."+E;H=!1;location.hash=v;setTimeout(function(){H=!0},1)}})}return function(){c.forEach(k)}}};var L=0;Prism.hooks.add("before-sanity-check",function(e){var b=e.element.parentElement;if(x(b)){var z=0;h(".line-highlight",
b).forEach(function(n){z+=n.textContent.length;n.parentNode.removeChild(n)});z&&/^(?: \n)+$/.test(e.code.slice(-z))&&(e.code=e.code.slice(0,-z))}});Prism.hooks.add("complete",function z(b){var n=b.element.parentElement;if(x(n)){clearTimeout(L);var m=Prism.plugins.lineNumbers;b=b.plugins&&b.plugins.lineNumbers;n.classList.contains("line-numbers")&&m&&!b?Prism.hooks.add("line-numbers",z):(Prism.plugins.lineHighlight.highlightLines(n)(),L=setTimeout(K,1))}});window.addEventListener("hashchange",K);window.addEventListener("resize",
function(){h("pre").filter(x).map(function(b){return Prism.plugins.lineHighlight.highlightLines(b)}).forEach(k)})}})();